/**
 * DNA | Profile & Identity Hub — Cross-C Identity Type System
 *
 * The Profile is where every C converges. It is not a static page — it is a
 * living, breathing representation of a user's entire DNA journey: who they
 * connect with, events they convene, spaces they collaborate in, value they
 * contribute, and stories they convey.
 *
 * Four Identity Layers:
 * - Layer 1: Professional Identity (Foundation — user-entered)
 * - Layer 2: Diaspora Identity (Cultural — user-curated)
 * - Layer 3: Activity (Living — auto-populated from Five C's)
 * - Layer 4: Impact (Emergent — generated by DIA)
 *
 * Dependencies: DIA Core Engine, Feed Architecture, Post Composer,
 *               Notification System, Messaging System
 */

import type { FiveCModule, SubscriptionTier } from './dia';

// ============================================================
// PROFILE — Core Identity
// ============================================================

export interface IdentityHubProfile {
  id: string;
  userId: string;

  // ── Layer 1: Professional Identity ──
  displayName: string;
  firstName: string;
  lastName: string;
  headline: string | null;
  bio: string | null;
  avatarUrl: string | null;
  coverImageUrl: string | null;
  location: ProfileLocation;
  pronouns: string | null;

  // Professional
  skills: ProfileSkill[];
  interests: ProfileInterest[];
  industry: string | null;
  experience: ProfileExperience[];
  education: ProfileEducation[];
  socialLinks: ProfileSocialLink[];

  // ── Layer 2: Diaspora Identity ──
  heritage: DiasporaHeritage;

  // ── Layer 3: Activity (auto-populated) ──
  activitySummary: FiveCActivitySummary;

  // ── Layer 4: Impact (DIA-generated) ──
  impactScore: FiveCImpactScore;
  badges: ProfileBadge[];
  diaInsight: string | null;

  // Profile meta
  completionPercentage: number;
  completionChecklist: CompletionChecklistItem[];
  verificationStatus: VerificationStatus;
  tier: UserTier;
  visibility: ProfileVisibility;
  profileViews: number;
  lastActiveAt: Date;
  joinedAt: Date;
  updatedAt: Date;
}

// ============================================================
// LOCATION
// ============================================================

export interface ProfileLocation {
  city: string | null;
  state: string | null;
  country: string;
  countryCode: string;
  timezone: string;
  coordinates: {
    latitude: number;
    longitude: number;
  } | null;
  displayFormat: string;
}

// ============================================================
// SKILLS & INTERESTS
// ============================================================

export interface ProfileSkill {
  id: string;
  name: string;
  category: SkillCategory;
  endorsementCount: number;
  endorsedBy: string[];
  isTopSkill: boolean;
  diaStrength: number;
  source: 'user_added' | 'dia_suggested' | 'endorsed';
}

export type SkillCategory =
  | 'technical' | 'business' | 'creative' | 'leadership'
  | 'research' | 'community' | 'language' | 'industry_specific';

export interface ProfileInterest {
  id: string;
  name: string;
  category: InterestCategory;
  addedAt: Date;
}

export type InterestCategory =
  | 'professional' | 'cultural' | 'geographic' | 'topical'
  | 'industry' | 'cause' | 'community';

// ============================================================
// DIASPORA HERITAGE (Layer 2)
// ============================================================

export interface DiasporaHeritage {
  heritageCountries: HeritageCountry[];
  currentCountry: string;
  languages: HeritageLanguage[];
  diasporaGeneration: DiasporaGeneration | null;
  culturalInterests: string[];
  diasporaEngagement: DiasporaEngagementLevel;
  regionalConnections: RegionalConnection[];
}

export interface HeritageCountry {
  countryCode: string;
  countryName: string;
  relationship: 'born' | 'ancestry' | 'lived' | 'connected';
  region: AfricanRegion;
  isPrimary: boolean;
}

export interface HeritageLanguage {
  language: string;
  proficiency: 'native' | 'fluent' | 'conversational' | 'learning';
  isHeritage: boolean;
}

export type DiasporaGeneration =
  | 'first'
  | 'second'
  | 'third_plus'
  | 'returnee'
  | 'continental'
  | 'ally';

export type DiasporaEngagementLevel =
  | 'exploring'
  | 'connecting'
  | 'contributing'
  | 'leading'
  | 'transforming';

export type AfricanRegion =
  | 'west_africa' | 'east_africa' | 'southern_africa'
  | 'north_africa' | 'central_africa';

export interface RegionalConnection {
  region: AfricanRegion;
  connectionCount: number;
  strength: 'strong' | 'moderate' | 'emerging';
}

// ============================================================
// EXPERIENCE & EDUCATION
// ============================================================

export interface ProfileExperience {
  id: string;
  title: string;
  organization: string;
  organizationLogoUrl: string | null;
  location: string | null;
  startDate: Date;
  endDate: Date | null;
  isCurrent: boolean;
  description: string | null;
  skills: string[];
  isAfricaFocused: boolean;
}

export interface ProfileEducation {
  id: string;
  institution: string;
  degree: string | null;
  fieldOfStudy: string | null;
  startYear: number;
  endYear: number | null;
  description: string | null;
  isHBCU: boolean;
  isAfricanInstitution: boolean;
}

// ============================================================
// SOCIAL LINKS
// ============================================================

export interface ProfileSocialLink {
  platform: SocialPlatform;
  url: string;
  username: string | null;
}

export type SocialPlatform =
  | 'linkedin' | 'twitter' | 'instagram' | 'github'
  | 'website' | 'youtube' | 'tiktok' | 'medium'
  | 'substack' | 'behance' | 'dribbble' | 'other';

// ============================================================
// FIVE C's ACTIVITY SUMMARY (Layer 3)
// ============================================================

export interface FiveCActivitySummary {
  connect: {
    connectionCount: number;
    countrySpan: number;
    recentConnectionCount: number;
    mutualConnectionsWithViewer: number;
  };
  convene: {
    eventsHosted: number;
    eventsAttended: number;
    upcomingEvents: number;
    totalAttendees: number;
  };
  collaborate: {
    spacesActive: number;
    spacesLed: number;
    tasksCompleted: number;
    collaboratorsCount: number;
  };
  contribute: {
    opportunitiesPosted: number;
    opportunitiesFulfilled: number;
    offersActive: number;
    needsActive: number;
  };
  convey: {
    storiesPublished: number;
    totalEngagement: number;
    followerCount: number;
    avgEngagementRate: number;
  };
}

// ============================================================
// FIVE C's IMPACT SCORE (Layer 4 — DIA-generated)
// ============================================================

export type CModule = FiveCModule;

export interface FiveCImpactScore {
  overall: number;
  connect: number;
  convene: number;
  collaborate: number;
  contribute: number;
  convey: number;
  lastComputedAt: Date;
  trend: 'rising' | 'stable' | 'declining';
  percentileRank: number;
  strongestC: CModule;
  growthOpportunityC: CModule;
}

// ============================================================
// PROFILE BADGES (Layer 4)
// ============================================================

export interface ProfileBadge {
  id: string;
  type: BadgeType;
  name: string;
  description: string;
  iconUrl: string;
  cModule: CModule | 'cross_c';
  earnedAt: Date;
  isDisplayed: boolean;
}

export type BadgeType =
  // CONNECT
  | 'connector_10'
  | 'connector_50'
  | 'connector_100'
  | 'global_networker'
  | 'bridge_builder'
  // CONVENE
  | 'event_host'
  | 'serial_host'
  | 'event_champion'
  | 'community_gatherer'
  // COLLABORATE
  | 'space_creator'
  | 'project_completer'
  | 'team_player'
  | 'task_master'
  // CONTRIBUTE
  | 'first_offer'
  | 'marketplace_active'
  | 'skill_sharer'
  | 'opportunity_creator'
  // CONVEY
  | 'storyteller'
  | 'thought_leader'
  | 'series_creator'
  | 'trending_voice'
  // CROSS-C
  | 'five_c_explorer'
  | 'five_c_master'
  | 'alpha_pioneer'
  | 'early_adopter'
  | 'heritage_ambassador'
  | 'verified_member';

// ============================================================
// PROFILE COMPLETION
// ============================================================

export interface CompletionChecklistItem {
  id: string;
  section: ProfileSection;
  label: string;
  isComplete: boolean;
  weight: number;
  diaMessage: string | null;
}

export type ProfileSection =
  | 'avatar' | 'cover_image' | 'headline' | 'bio'
  | 'location' | 'heritage' | 'languages' | 'skills'
  | 'interests' | 'experience' | 'education' | 'social_links'
  | 'first_post' | 'first_connection' | 'first_event'
  | 'first_space' | 'first_story';

export const PROFILE_COMPLETION_WEIGHTS: Record<ProfileSection, number> = {
  avatar: 10,
  cover_image: 3,
  headline: 8,
  bio: 7,
  location: 5,
  heritage: 10,
  languages: 5,
  skills: 10,
  interests: 5,
  experience: 7,
  education: 5,
  social_links: 3,
  first_post: 5,
  first_connection: 7,
  first_event: 3,
  first_space: 3,
  first_story: 4,
};

// ============================================================
// VERIFICATION
// ============================================================

export enum VerificationStatus {
  UNVERIFIED = 'unverified',
  PENDING = 'pending',
  VERIFIED = 'verified',
  PRO_VERIFIED = 'pro_verified',
}

export interface VerificationBadgeConfig {
  status: VerificationStatus;
  icon: string;
  color: string;
  label: string;
  tooltip: string;
}

export const VERIFICATION_BADGE_CONFIGS: Record<VerificationStatus, VerificationBadgeConfig> = {
  [VerificationStatus.UNVERIFIED]: { status: VerificationStatus.UNVERIFIED, icon: '', color: '', label: '', tooltip: '' },
  [VerificationStatus.PENDING]: { status: VerificationStatus.PENDING, icon: 'clock', color: '#C4942A', label: 'Verification Pending', tooltip: 'Identity verification in progress' },
  [VerificationStatus.VERIFIED]: { status: VerificationStatus.VERIFIED, icon: 'check-circle', color: '#4A8D77', label: 'Verified', tooltip: 'Verified DNA member' },
  [VerificationStatus.PRO_VERIFIED]: { status: VerificationStatus.PRO_VERIFIED, icon: 'shield-check', color: '#B87333', label: 'Pro', tooltip: 'DNA Pro verified member' },
};

// ============================================================
// USER TIER
// ============================================================

export type UserTier = SubscriptionTier;

// ============================================================
// PROFILE VISIBILITY
// ============================================================

export interface ProfileVisibility {
  profileDiscoverable: boolean;
  showActivity: 'everyone' | 'connections' | 'none';
  showConnections: 'everyone' | 'connections' | 'none';
  showHeritage: 'everyone' | 'connections' | 'none';
  showExperience: 'everyone' | 'connections' | 'none';
  showContributions: 'everyone' | 'connections' | 'none';
  showImpactScore: 'everyone' | 'connections' | 'none';
  showBadges: boolean;
  showOnlineStatus: boolean;
}

export const DEFAULT_PROFILE_VISIBILITY: ProfileVisibility = {
  profileDiscoverable: true,
  showActivity: 'connections',
  showConnections: 'connections',
  showHeritage: 'everyone',
  showExperience: 'everyone',
  showContributions: 'connections',
  showImpactScore: 'connections',
  showBadges: true,
  showOnlineStatus: true,
};

// ============================================================
// PROFILE VIEW CONTEXT
// ============================================================

export type ProfileViewContext =
  | 'own_profile'
  | 'connected'
  | 'not_connected'
  | 'search_result'
  | 'dia_suggestion'
  | 'event_attendee'
  | 'space_member'
  | 'opportunity_poster';

export interface ParticipantPreview {
  id: string;
  displayName: string;
  avatarUrl: string | null;
  headline: string | null;
}

export interface ProfileViewPayload {
  profile: IdentityHubProfile;
  viewContext: ProfileViewContext;
  viewerRelationship: {
    isConnected: boolean;
    isPending: boolean;
    mutualConnectionCount: number;
    mutualConnections: ParticipantPreview[];
    sharedSpaces: { id: string; name: string }[];
    sharedEvents: { id: string; name: string }[];
    relationshipStrength: number | null;
  };
  diaMatchInfo: {
    matchScore: number | null;
    matchType: string | null;
    matchReasons: string[];
  } | null;
  visibleSections: ProfileSection[];
}

// ============================================================
// PROFILE LAYOUT CONSTANTS
// ============================================================

export const PROFILE_LAYOUT = {
  header: {
    coverHeight: { mobile: 180, desktop: 240 },
    avatarSize: { mobile: 96, desktop: 120 },
    avatarOffset: -48,
    nameSize: { mobile: 24, desktop: 28 },
    headlineSize: { mobile: 15, desktop: 16 },
    headlineColor: '#666666',
    verificationBadgeSize: 20,
  },
  heritageCard: {
    backgroundColor: '#F9F7F4',
    borderLeft: '3px solid #B87333',
    flagSize: 24,
    flagSpacing: 8,
    generationBadge: {
      fontSize: 12,
      backgroundColor: '#4A8D77',
      textColor: '#FFFFFF',
      borderRadius: 12,
    },
  },
  impactRadar: {
    size: { mobile: 200, desktop: 260 },
    colors: {
      connect: '#4A8D77',
      convene: '#C4942A',
      collaborate: '#2D5A3D',
      contribute: '#B87333',
      convey: '#2A7A8C',
    },
    fillOpacity: 0.2,
    strokeWidth: 2,
  },
  section: {
    titleSize: 18,
    titleFont: 'Georgia',
    titleColor: '#2D5A3D',
    padding: 16,
    gap: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: 'rgba(0,0,0,0.04)',
  },
  badges: {
    maxDisplayed: 5,
    size: 40,
    spacing: 8,
    glowOnRecent: true,
  },
  culturalPattern: {
    enabled: true,
    opacity: 0.03,
    pattern: 'kente' as CulturalPattern,
    options: ['kente', 'ndebele', 'mudcloth', 'adinkra', 'none'] as CulturalPattern[],
  },
  mobileSectionOrder: [
    'header',
    'heritage_card',
    'bio',
    'five_c_impact',
    'featured_content',
    'skills_interests',
    'activity_feed',
    'connections',
    'experience_education',
    'spaces',
    'events',
    'contributions',
    'stories',
    'badges',
  ] as const,
};

export type CulturalPattern = 'kente' | 'ndebele' | 'mudcloth' | 'adinkra' | 'none';

// ============================================================
// PROFILE EDIT LAYOUT
// ============================================================

export interface ProfileEditTab {
  id: string;
  label: string;
  icon: string;
  sections: string[];
}

export const PROFILE_EDIT_TABS: ProfileEditTab[] = [
  { id: 'basic', label: 'Basic Info', icon: 'user', sections: ['avatar', 'cover', 'name', 'headline', 'bio', 'pronouns'] },
  { id: 'heritage', label: 'Heritage', icon: 'globe', sections: ['heritageCountries', 'languages', 'generation', 'culturalInterests'] },
  { id: 'professional', label: 'Professional', icon: 'briefcase', sections: ['skills', 'interests', 'industry', 'experience', 'education'] },
  { id: 'links', label: 'Links', icon: 'link', sections: ['socialLinks'] },
  { id: 'privacy', label: 'Privacy', icon: 'eye', sections: ['visibility', 'profileDiscoverable'] },
];

export interface PatternOption {
  id: CulturalPattern;
  label: string;
  origin: string;
  preview: string | null;
}

export const CULTURAL_PATTERN_OPTIONS: PatternOption[] = [
  { id: 'kente', label: 'Kente', origin: 'Ghana', preview: '/patterns/kente-thumb.svg' },
  { id: 'ndebele', label: 'Ndebele', origin: 'South Africa', preview: '/patterns/ndebele-thumb.svg' },
  { id: 'mudcloth', label: 'Mudcloth', origin: 'Mali', preview: '/patterns/mudcloth-thumb.svg' },
  { id: 'adinkra', label: 'Adinkra', origin: 'Ghana', preview: '/patterns/adinkra-thumb.svg' },
  { id: 'none', label: 'None', origin: '', preview: null },
];

// ============================================================
// MONETIZATION / TIER FEATURE GATES
// ============================================================

export interface ProfileTierGate {
  skillsLimit: number;
  completionNudges: 'basic' | 'dia_powered';
  verificationBadge: 'email_only' | 'full' | 'org';
  profileAnalytics: 'view_count' | 'who_viewed_context_trend' | 'team_analytics';
  featuredContentSlots: number;
  culturalPatternOverlay: 'default' | 'all' | 'custom';
  diaInsight: boolean;
  impactScoreDetail: 'overall_only' | 'full_breakdown_trend' | 'team_dashboard';
  badgeDisplayMax: number;
  visibilityControls: 'basic' | 'full_granular' | 'full_org';
  customProfileUrl: boolean;
  exportProfileData: boolean;
}

export const PROFILE_TIER_GATES: Record<UserTier, ProfileTierGate> = {
  free: {
    skillsLimit: 10,
    completionNudges: 'basic',
    verificationBadge: 'email_only',
    profileAnalytics: 'view_count',
    featuredContentSlots: 1,
    culturalPatternOverlay: 'default',
    diaInsight: false,
    impactScoreDetail: 'overall_only',
    badgeDisplayMax: 3,
    visibilityControls: 'basic',
    customProfileUrl: false,
    exportProfileData: false,
  },
  pro: {
    skillsLimit: 20,
    completionNudges: 'dia_powered',
    verificationBadge: 'full',
    profileAnalytics: 'who_viewed_context_trend',
    featuredContentSlots: 3,
    culturalPatternOverlay: 'all',
    diaInsight: true,
    impactScoreDetail: 'full_breakdown_trend',
    badgeDisplayMax: 5,
    visibilityControls: 'full_granular',
    customProfileUrl: true,
    exportProfileData: true,
  },
  org: {
    skillsLimit: Infinity,
    completionNudges: 'dia_powered',
    verificationBadge: 'org',
    profileAnalytics: 'team_analytics',
    featuredContentSlots: 5,
    culturalPatternOverlay: 'custom',
    diaInsight: true,
    impactScoreDetail: 'team_dashboard',
    badgeDisplayMax: Infinity,
    visibilityControls: 'full_org',
    customProfileUrl: true,
    exportProfileData: true,
  },
};

// ============================================================
// GENERATION LABELS
// ============================================================

export const DIASPORA_GENERATION_LABELS: Record<DiasporaGeneration, string> = {
  first: 'First Generation - Born in Africa, living abroad',
  second: 'Second Generation - Parents from Africa',
  third_plus: 'Third+ Generation - Grandparents+ from Africa',
  returnee: 'Returnee - Returned to Africa',
  continental: 'Continental - Born and living in Africa',
  ally: 'Ally - Committed to the mission',
};

export const DIASPORA_ENGAGEMENT_LABELS: Record<DiasporaEngagementLevel, string> = {
  exploring: 'Exploring - New to diaspora engagement',
  connecting: 'Connecting - Building connections',
  contributing: 'Contributing - Actively giving back',
  leading: 'Leading - Leading initiatives',
  transforming: 'Transforming - Driving systemic change',
};

export const AFRICAN_REGION_LABELS: Record<AfricanRegion, string> = {
  west_africa: 'West Africa',
  east_africa: 'East Africa',
  southern_africa: 'Southern Africa',
  north_africa: 'North Africa',
  central_africa: 'Central Africa',
};
