// Rich seed data for professionals - 20 diverse diaspora changemakers

export interface MockProfessional {
  id: string;
  name: string;
  title: string;
  company: string;
  location: string;
  origin: string;
  avatar: string;
  followers: number;
  connections: number;
  skills: string[];
  bio: string;
  connectionStatus: 'connected' | 'pending' | null;
  recentActivity: string;
  isOnline: boolean;
  mutualConnections: number;
}

export const mockProfessionals: MockProfessional[] = [
  {
    id: 'prof-1',
    name: 'Dr. Amara Okonkwo',
    title: 'Public Health Physician & Global Health Consultant',
    company: 'Independent',
    location: 'Toronto, Canada',
    origin: 'Nigeria',
    avatar: '',
    followers: 342,
    connections: 287,
    skills: ['Infectious disease prevention', 'Maternal and child health', 'Health systems design', 'Community health training', 'Policy advocacy'],
    bio: 'Dr. Okonkwo specializes in infectious disease prevention and maternal health. After completing her medical degree in Nigeria and a Master\'s in Public Health at Johns Hopkins, she has spent 15 years working across three continents on health systems strengthening. Wants to establish telemedicine networks connecting African diaspora doctors with underserved communities in their home countries.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: false,
    mutualConnections: 5,
  },
  {
    id: 'prof-2',
    name: 'Luis Chen-Martinez',
    title: 'Sustainable Fashion Designer & Social Entrepreneur',
    company: 'Independent',
    location: 'Berlin, Germany',
    origin: 'Peru',
    avatar: '',
    followers: 521,
    connections: 412,
    skills: ['Sustainable fashion design', 'Textile innovation', 'Artisan collaboration', 'Supply chain ethics', 'Cultural design fusion'],
    bio: 'Growing up in Lima\'s vibrant Chinatown district, Luis witnessed his grandmother\'s textile business struggle against fast fashion. He studied fashion design in London and launched an ethical fashion brand that employs artisans from Peru and trains young designers in sustainable practices.',
    connectionStatus: null,
    recentActivity: 'Posted 2 days ago',
    isOnline: true,
    mutualConnections: 8,
  },
  {
    id: 'prof-3',
    name: 'Ravi Subramanian',
    title: 'Tech Executive & Angel Investor',
    company: 'Independent',
    location: 'Melbourne, Australia',
    origin: 'India',
    avatar: '',
    followers: 1240,
    connections: 856,
    skills: ['Software architecture', 'Startup scaling', 'Tech leadership', 'Angel investing', 'Mentorship programs'],
    bio: 'Former VP of Engineering at major tech companies, Ravi has 30+ years in software development and technology leadership. He\'s passionate about increasing representation of South Asian founders in the startup ecosystem and has invested in over 40 early-stage companies.',
    connectionStatus: null,
    recentActivity: 'Commented on your post',
    isOnline: false,
    mutualConnections: 12,
  },
  {
    id: 'prof-4',
    name: 'Fatima Al-Rashid',
    title: 'Education Technology Specialist & Refugee Advocate',
    company: 'UNESCO',
    location: 'Stockholm, Sweden',
    origin: 'Syria',
    avatar: '',
    followers: 687,
    connections: 534,
    skills: ['Educational technology', 'Digital literacy', 'Refugee integration', 'Language learning platforms', 'Mobile app development'],
    bio: 'Forced to flee Syria in 2014, Fatima arrived in Sweden as a refugee with a background in computer science. She built language-learning apps specifically designed for refugees and now works with UNESCO on digital education initiatives for displaced populations.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 7,
  },
  {
    id: 'prof-5',
    name: 'Marcus Thompson',
    title: 'Urban Agriculture Expert & Food Justice Activist',
    company: 'Independent',
    location: 'Atlanta, USA',
    origin: 'Jamaica',
    avatar: '',
    followers: 432,
    connections: 389,
    skills: ['Urban agriculture', 'Food justice', 'Community organizing', 'Sustainable farming', 'Youth employment programs'],
    bio: 'Growing up in Kingston, Marcus learned farming from his grandfather. After studying agricultural science in the US, he\'s spent a decade developing urban farming models that bring fresh food to food deserts while creating jobs. His organization has established 50+ community gardens across the American South.',
    connectionStatus: null,
    recentActivity: 'Posted 1 week ago',
    isOnline: false,
    mutualConnections: 4,
  },
  {
    id: 'prof-6',
    name: 'Dr. Yuki Tanaka',
    title: 'Robotics Engineer & AI Ethics Researcher',
    company: 'Independent',
    location: 'São Paulo, Brazil',
    origin: 'Japan',
    avatar: '',
    followers: 892,
    connections: 645,
    skills: ['Robotics engineering', 'AI ethics', 'Assistive technology', 'Machine learning', 'Accessibility design'],
    bio: 'Dr. Tanaka worked for leading Japanese robotics companies before relocating to Brazil with her Brazilian husband. She now leads a research lab focusing on AI applications for accessibility and inclusion, particularly for Portuguese-speaking communities often left out of AI development.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 15,
  },
  {
    id: 'prof-7',
    name: 'Ibrahim Hassan',
    title: 'Fintech Entrepreneur & Mobile Payment Innovator',
    company: 'Independent',
    location: 'Dubai, UAE',
    origin: 'Somalia',
    avatar: '',
    followers: 1034,
    connections: 723,
    skills: ['Fintech development', 'Mobile payments', 'Remittance systems', 'Financial inclusion', 'Blockchain technology'],
    bio: 'After his family relocated to Dubai, Ibrahim studied finance and computer science. He founded a mobile payment platform that makes it easier and cheaper for diaspora communities to send remittances home, having processed over $500M in transactions across East Africa.',
    connectionStatus: null,
    recentActivity: 'Posted 3 days ago',
    isOnline: false,
    mutualConnections: 9,
  },
  {
    id: 'prof-8',
    name: 'Elena Popescu',
    title: 'Digital Rights Lawyer & Privacy Advocate',
    company: 'Independent',
    location: 'Paris, France',
    origin: 'Romania',
    avatar: '',
    followers: 567,
    connections: 421,
    skills: ['Digital rights law', 'Data protection (GDPR)', 'Privacy advocacy', 'Internet governance', 'Human rights law'],
    bio: 'Elena witnessed internet censorship and digital rights violations in Eastern Europe. She studied law in Romania and France, specializing in data protection and digital rights. She now represents NGOs and individuals fighting surveillance and protecting online freedom.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 6,
  },
  {
    id: 'prof-9',
    name: 'Kwame Mensah',
    title: 'Renewable Energy Engineer & Climate Finance Specialist',
    company: 'Independent',
    location: 'Amsterdam, Netherlands',
    origin: 'Ghana',
    avatar: '',
    followers: 945,
    connections: 678,
    skills: ['Renewable energy systems', 'Climate finance', 'Project development', 'Solar/wind engineering', 'Carbon markets'],
    bio: 'With degrees in electrical engineering and an MBA in sustainable finance, Kwame has spent 25 years developing renewable energy projects across Africa. He now structures climate finance deals and helps African countries access green bonds and climate adaptation funding.',
    connectionStatus: null,
    recentActivity: 'Posted 5 days ago',
    isOnline: false,
    mutualConnections: 11,
  },
  {
    id: 'prof-10',
    name: 'Mei Lin Wu',
    title: 'Mental Health Counselor & Cultural Competency Trainer',
    company: 'Independent',
    location: 'Vancouver, Canada',
    origin: 'Taiwan',
    avatar: '',
    followers: 423,
    connections: 356,
    skills: ['Multicultural counseling', 'Immigration trauma', 'Identity development', 'Cultural competency training', 'Bilingual therapy'],
    bio: 'After experiencing cultural isolation as an immigrant, Mei Lin became a licensed therapist specializing in diaspora mental health. She provides culturally sensitive therapy and trains other mental health professionals to better serve immigrant and diaspora communities.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 3,
  },
  {
    id: 'prof-11',
    name: 'Carlos Gutierrez',
    title: 'Immigration Attorney & Policy Advocate',
    company: 'Independent',
    location: 'Washington DC, USA',
    origin: 'El Salvador',
    avatar: '',
    followers: 712,
    connections: 589,
    skills: ['Immigration law', 'Asylum cases', 'Policy advocacy', 'Unaccompanied minors', 'Legal aid coordination'],
    bio: 'Carlos came to the US as a teenager during El Salvador\'s civil war. After law school, he\'s dedicated his career to representing unaccompanied minors and asylum seekers. He\'s testified before Congress and helped draft immigration reform proposals.',
    connectionStatus: null,
    recentActivity: 'Posted 1 day ago',
    isOnline: false,
    mutualConnections: 14,
  },
  {
    id: 'prof-12',
    name: 'Priya Nair',
    title: 'Data Scientist & Healthcare Analytics Specialist',
    company: 'Independent',
    location: 'Singapore, Singapore',
    origin: 'India',
    avatar: '',
    followers: 634,
    connections: 487,
    skills: ['Machine learning', 'Healthcare analytics', 'Predictive modeling', 'Data visualization', 'Statistical analysis'],
    bio: 'A mathematics prodigy, Priya completed her PhD at 24 and now uses machine learning to predict disease outbreaks and optimize healthcare delivery in Southeast Asia. She\'s particularly focused on using data to improve maternal health outcomes.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 10,
  },
  {
    id: 'prof-13',
    name: 'Ahmed Karim',
    title: 'Documentary Filmmaker & Storyteller',
    company: 'Independent',
    location: 'Manchester, UK',
    origin: 'Pakistan',
    avatar: '',
    followers: 823,
    connections: 612,
    skills: ['Documentary filmmaking', 'Storytelling', 'Video production', 'Cultural documentation', 'Media for social change'],
    bio: 'Ahmed\'s films focus on untold stories of diaspora communities, migration, and cultural identity. His documentaries have won international awards and screen at major film festivals. He uses film as a tool for social change and cross-cultural understanding.',
    connectionStatus: null,
    recentActivity: 'Posted 4 days ago',
    isOnline: false,
    mutualConnections: 7,
  },
  {
    id: 'prof-14',
    name: 'Natalia Volkov',
    title: 'Cybersecurity Expert & Tech Infrastructure Consultant',
    company: 'Independent',
    location: 'Lisbon, Portugal',
    origin: 'Ukraine',
    avatar: '',
    followers: 756,
    connections: 534,
    skills: ['Cybersecurity', 'Infrastructure protection', 'Risk assessment', 'Security training', 'Crisis response'],
    bio: 'With 20 years in cybersecurity, Natalia has protected critical infrastructure for governments and major corporations. Since the war in Ukraine, she\'s focused on helping NGOs and humanitarian organizations strengthen their digital security to protect vulnerable populations.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 8,
  },
  {
    id: 'prof-15',
    name: 'Javier Rodríguez',
    title: 'Social Media Strategist & Digital Entrepreneur',
    company: 'Independent',
    location: 'Miami, USA',
    origin: 'Cuba',
    avatar: '',
    followers: 489,
    connections: 392,
    skills: ['Social media marketing', 'Digital strategy', 'Content creation', 'Brand development', 'Community management'],
    bio: 'Growing up with limited internet access in Cuba, Javier became fascinated with digital communication. After immigrating to the US, he built a successful digital marketing agency and now helps immigrant-owned businesses and nonprofits build their online presence.',
    connectionStatus: null,
    recentActivity: 'Posted 2 weeks ago',
    isOnline: false,
    mutualConnections: 5,
  },
  {
    id: 'prof-16',
    name: 'Dr. Aisha Mohammed',
    title: 'Historian & Cultural Heritage Preservationist',
    company: 'Independent',
    location: 'London, UK',
    origin: 'Sudan',
    avatar: '',
    followers: 678,
    connections: 523,
    skills: ['African history', 'Digital archiving', 'Museum curation', 'Cultural preservation', 'Academic research'],
    bio: 'Dr. Mohammed specializes in African diaspora history and digital archiving. She\'s worked with museums globally to decolonize their collections and has led projects digitizing endangered historical documents and artifacts from across Africa.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 13,
  },
  {
    id: 'prof-17',
    name: 'Thanh Nguyen',
    title: 'Game Developer & Interactive Media Designer',
    company: 'Independent',
    location: 'Sydney, Australia',
    origin: 'Vietnam',
    avatar: '',
    followers: 512,
    connections: 434,
    skills: ['Game development', 'Interactive storytelling', 'Unity/Unreal Engine', 'Narrative design', 'Cultural education games'],
    bio: 'Thanh creates video games that explore cultural identity, migration stories, and historical narratives often missing from mainstream gaming. His indie game about the Vietnamese diaspora experience won multiple awards and is used in schools to teach immigration history.',
    connectionStatus: null,
    recentActivity: 'Posted 6 days ago',
    isOnline: false,
    mutualConnections: 6,
  },
  {
    id: 'prof-18',
    name: 'Rosa Martinez',
    title: 'Community Organizer & Workers\' Rights Advocate',
    company: 'Independent',
    location: 'Los Angeles, USA',
    origin: 'Guatemala',
    avatar: '',
    followers: 845,
    connections: 687,
    skills: ['Labor organizing', 'Workers\' rights', 'Community mobilization', 'Popular education', 'Coalition building'],
    bio: 'Rosa has spent 35 years organizing domestic workers, garment workers, and other immigrant laborers. She\'s founded worker centers, led successful campaigns for labor protections, and trained thousands of workers to know and fight for their rights.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 16,
  },
  {
    id: 'prof-19',
    name: 'Dr. Olumide Adeyemi',
    title: 'Biotechnology Researcher & Agricultural Scientist',
    company: 'Independent',
    location: 'Copenhagen, Denmark',
    origin: 'Nigeria',
    avatar: '',
    followers: 567,
    connections: 445,
    skills: ['Agricultural biotechnology', 'Plant genetics', 'Climate adaptation', 'Food security', 'Research & development'],
    bio: 'Dr. Adeyemi\'s research focuses on developing climate-resilient crops for African agriculture. With a PhD in plant genetics, he works at the intersection of traditional agricultural knowledge and cutting-edge biotechnology to address food security challenges.',
    connectionStatus: null,
    recentActivity: 'Posted 1 week ago',
    isOnline: false,
    mutualConnections: 9,
  },
  {
    id: 'prof-20',
    name: 'Samira Kazemi',
    title: 'VR/AR Developer & Immersive Experience Designer',
    company: 'Independent',
    location: 'Toronto, Canada',
    origin: 'Iran',
    avatar: '',
    followers: 723,
    connections: 589,
    skills: ['Virtual reality development', 'Augmented reality', '3D modeling', 'Immersive storytelling', 'Unity development'],
    bio: 'Samira creates virtual reality experiences that transport people to places they can\'t physically visit, whether due to conflict, borders, or physical limitations. Her VR project \'Homeland\' allows diaspora children to virtually explore their parents\' and grandparents\' home cities.',
    connectionStatus: null,
    recentActivity: 'Active on DNA',
    isOnline: true,
    mutualConnections: 11,
  },
];
