
export const mockProfessionals = [
  {
    id: '1',
    name: 'Dr. Amara Okafor',
    title: 'Senior FinTech Product Manager',
    company: 'Stripe',
    location: 'London, UK',
    origin: 'Lagos, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 2340,
    connections: 890,
    skills: ['Product Strategy', 'Financial Technology', 'Team Leadership'],
    bio: 'Passionate about building financial infrastructure that empowers African businesses globally. 5+ years at top fintech companies.',
    connectionStatus: null,
    recentActivity: 'Published: "The Future of Cross-Border Payments in Africa"',
    isOnline: true,
    mutualConnections: 12
  },
  {
    id: '2',
    name: 'Prof. Kwame Asante',
    title: 'Agricultural Innovation Lead',
    company: 'World Bank Group',
    location: 'Toronto, Canada',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1200,
    skills: ['AgriTech', 'Sustainable Development', 'Research'],
    bio: 'Leading agricultural transformation initiatives across sub-Saharan Africa. PhD in Agricultural Economics.',
    connectionStatus: 'connected',
    recentActivity: 'Shared insights on climate-smart farming',
    isOnline: false,
    mutualConnections: 8
  },
  {
    id: '3',
    name: 'Sarah Mwangi',
    title: 'Impact Investment Principal',
    company: 'TLcom Capital',
    location: 'Nairobi, Kenya',
    origin: 'Nairobi, Kenya',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    followers: 3450,
    connections: 750,
    skills: ['Impact Investing', 'Venture Capital', 'ESG'],
    bio: 'Investing in early-stage African startups solving real problems. Former McKinsey consultant with 8+ years experience.',
    connectionStatus: 'pending',
    recentActivity: 'Attended African Startup Summit 2024',
    isOnline: true,
    mutualConnections: 15
  },
  {
    id: '4',
    name: 'Ibrahim Hassan',
    title: 'Tech Entrepreneur',
    company: 'Flutterwave',
    location: 'San Francisco, USA',
    origin: 'Cairo, Egypt',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 4200,
    connections: 980,
    skills: ['Fintech', 'Entrepreneurship', 'Market Expansion'],
    bio: 'Building payment solutions for Africa. Previously scaled tech teams across 3 continents.',
    connectionStatus: null,
    recentActivity: 'Launched new payment gateway for SMEs',
    isOnline: true,
    mutualConnections: 22
  },
  {
    id: '5',
    name: 'Dr. Fatima Al-Rashid',
    title: 'Climate Tech Researcher',
    company: 'MIT',
    location: 'Boston, USA',
    origin: 'Marrakech, Morocco',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 650,
    skills: ['Climate Technology', 'Renewable Energy', 'Policy'],
    bio: 'PhD researcher focusing on scalable climate solutions for MENA and Sub-Saharan Africa.',
    connectionStatus: null,
    recentActivity: 'Published research on solar energy adoption',
    isOnline: false,
    mutualConnections: 7
  },
  {
    id: '6',
    name: 'Kofi Mensah',
    title: 'Digital Health Innovator',
    company: 'mPharma',
    location: 'Accra, Ghana',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
    followers: 1850,
    connections: 420,
    skills: ['Healthcare Technology', 'Digital Health', 'Operations'],
    bio: 'Revolutionizing healthcare access across Africa through technology and innovative supply chain solutions.',
    connectionStatus: 'connected',
    recentActivity: 'Expanded operations to 3 new countries',
    isOnline: true,
    mutualConnections: 5
  }
];

export type MockProfessional = typeof mockProfessionals[0];
