
export const mockProfessionals = [
  {
    id: '1',
    name: 'Dr. Amara Okafor',
    title: 'Senior FinTech Product Manager',
    company: 'Stripe',
    location: 'London, UK',
    origin: 'Lagos, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face',
    followers: 2340,
    connections: 890,
    skills: ['Product Strategy', 'Financial Technology', 'Team Leadership'],
    bio: 'Passionate about building financial infrastructure that empowers African businesses globally. 5+ years at top fintech companies.',
    connectionStatus: null,
    recentActivity: 'Published: "The Future of Cross-Border Payments in Africa"',
    isOnline: true,
    mutualConnections: 12
  },
  {
    id: '2',
    name: 'Prof. Kwame Asante',
    title: 'Agricultural Innovation Lead',
    company: 'World Bank Group',
    location: 'Toronto, Canada',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1200,
    skills: ['AgriTech', 'Sustainable Development', 'Research'],
    bio: 'Leading agricultural transformation initiatives across sub-Saharan Africa. PhD in Agricultural Economics.',
    connectionStatus: 'connected',
    recentActivity: 'Shared insights on climate-smart farming',
    isOnline: false,
    mutualConnections: 8
  },
  {
    id: '3',
    name: 'Sarah Mwangi',
    title: 'Impact Investment Principal',
    company: 'TLcom Capital',
    location: 'Nairobi, Kenya',
    origin: 'Nairobi, Kenya',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    followers: 3450,
    connections: 750,
    skills: ['Impact Investing', 'Venture Capital', 'ESG'],
    bio: 'Investing in early-stage African startups solving real problems. Former McKinsey consultant with 8+ years experience.',
    connectionStatus: 'pending',
    recentActivity: 'Attended African Startup Summit 2024',
    isOnline: true,
    mutualConnections: 15
  },
  {
    id: '4',
    name: 'Ibrahim Hassan',
    title: 'Tech Entrepreneur',
    company: 'Flutterwave',
    location: 'San Francisco, USA',
    origin: 'Cairo, Egypt',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 4200,
    connections: 980,
    skills: ['Fintech', 'Entrepreneurship', 'Market Expansion'],
    bio: 'Building payment solutions for Africa. Previously scaled tech teams across 3 continents.',
    connectionStatus: null,
    recentActivity: 'Launched new payment gateway for SMEs',
    isOnline: true,
    mutualConnections: 22
  },
  {
    id: '5',
    name: 'Dr. Fatima Al-Rashid',
    title: 'Climate Tech Researcher',
    company: 'MIT',
    location: 'Boston, USA',
    origin: 'Marrakech, Morocco',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 650,
    skills: ['Climate Technology', 'Renewable Energy', 'Policy'],
    bio: 'PhD researcher focusing on scalable climate solutions for MENA and Sub-Saharan Africa.',
    connectionStatus: null,
    recentActivity: 'Published research on solar energy adoption',
    isOnline: false,
    mutualConnections: 7
  },
  {
    id: '6',
    name: 'Kofi Mensah',
    title: 'Digital Health Innovator',
    company: 'mPharma',
    location: 'Accra, Ghana',
    origin: 'Accra, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
    followers: 1850,
    connections: 420,
    skills: ['Healthcare Technology', 'Digital Health', 'Operations'],
    bio: 'Revolutionizing healthcare access across Africa through technology and innovative supply chain solutions.',
    connectionStatus: 'connected',
    recentActivity: 'Expanded operations to 3 new countries',
    isOnline: true,
    mutualConnections: 5
  },
  {
    id: '7',
    name: 'Marcus Johnson',
    title: 'Cultural Heritage Director',
    company: 'Smithsonian Institution',
    location: 'Washington DC, USA',
    origin: 'African American Heritage',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    followers: 3200,
    connections: 780,
    skills: ['Cultural Preservation', 'Museum Curation', 'Educational Programs'],
    bio: 'Dedicated to preserving and showcasing African American history and its connections to the African continent.',
    connectionStatus: null,
    recentActivity: 'Launched "Diaspora Connections" exhibition',
    isOnline: true,
    mutualConnections: 18
  },
  {
    id: '8',
    name: 'Dr. Mariam Touré-Williams',
    title: 'Global Health Equity Specialist', 
    company: 'WHO',
    location: 'Geneva, Switzerland',
    origin: 'Bamako, Mali / Detroit, USA',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 4890,
    connections: 1340,
    skills: ['Public Health', 'Health Equity', 'International Development'],
    bio: 'Mali-born, Detroit-raised physician working to eliminate health disparities across Africa and the diaspora.',
    connectionStatus: 'connected',
    recentActivity: 'Published maternal health study across 12 countries',
    isOnline: false,
    mutualConnections: 31
  },
  {
    id: '9',
    name: 'Keisha Baptiste',
    title: 'Sustainable Fashion Entrepreneur',
    company: 'Caribbean Threads Collective',
    location: 'Port of Spain, Trinidad',
    origin: 'Afro-Caribbean Heritage',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b35d4e1c?w=150&h=150&fit=crop&crop=face',
    followers: 2670,
    connections: 540,
    skills: ['Sustainable Fashion', 'Ethical Manufacturing', 'Cultural Design'],
    bio: 'Bridging Caribbean and African textile traditions while building sustainable fashion supply chains.',
    connectionStatus: 'pending',
    recentActivity: 'Launched partnership with Ghana textile producers',
    isOnline: true,
    mutualConnections: 9
  },
  {
    id: '10',
    name: 'David Chen',
    title: 'Africa Tech Investment Director',
    company: 'Andreessen Horowitz',
    location: 'Silicon Valley, USA',
    origin: 'Ally - Chinese American',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 5230,
    connections: 1450,
    skills: ['Venture Capital', 'African Tech Ecosystem', 'Strategic Partnerships'],
    bio: 'Passionate ally investing in African tech startups. Focused on building bridges between Silicon Valley and African innovation.',
    connectionStatus: null,
    recentActivity: 'Led $15M Series A in Lagos-based startup',
    isOnline: true,
    mutualConnections: 28
  },
  {
    id: '11',
    name: 'Aisha Omar-Jackson',
    title: 'Renewable Energy Engineer',
    company: 'Tesla Energy',
    location: 'Austin, USA',
    origin: 'Mogadishu, Somalia / Atlanta, USA',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    followers: 3890,
    connections: 920,
    skills: ['Solar Engineering', 'Grid Infrastructure', 'Energy Storage'],
    bio: 'Somali-American engineer developing clean energy solutions for off-grid communities in Africa.',
    connectionStatus: 'connected',
    recentActivity: 'Deployed solar microgrids in 5 Kenyan villages',
    isOnline: true,
    mutualConnections: 16
  },
  {
    id: '12',
    name: 'Roberto Fernandez',
    title: 'Afro-Latin Cultural Ambassador',
    company: 'OAS Cultural Programs',
    location: 'Bogotá, Colombia',
    origin: 'Afro-Colombian Heritage',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 2340,
    connections: 680,
    skills: ['Cultural Diplomacy', 'Afro-Latin Studies', 'Community Organizing'],
    bio: 'Celebrating and preserving Afro-Latin connections to Africa through cultural exchange programs.',
    connectionStatus: null,
    recentActivity: 'Organized Pan-African Cultural Festival',
    isOnline: false,
    mutualConnections: 12
  },
  {
    id: '13',
    name: 'Dr. Thandiwe Nyong',
    title: 'AI Ethics Researcher',
    company: 'Google DeepMind',
    location: 'London, UK',
    origin: 'Cape Town, South Africa',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 6780,
    connections: 1890,
    skills: ['Artificial Intelligence', 'Ethics', 'Algorithmic Bias'],
    bio: 'Ensuring AI systems are fair and inclusive for African and global South communities.',
    connectionStatus: 'pending',
    recentActivity: 'Published "AI Bias in African Languages" paper',
    isOnline: true,
    mutualConnections: 45
  },
  {
    id: '14',
    name: 'Jamal Washington',
    title: 'Sports Development Director',
    company: 'NBA Africa',
    location: 'Johannesburg, South Africa',
    origin: 'African American Heritage',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 4560,
    connections: 1120,
    skills: ['Sports Management', 'Youth Development', 'International Relations'],
    bio: 'African American executive developing basketball talent across Africa and connecting youth with opportunities.',
    connectionStatus: 'connected',
    recentActivity: 'Launched youth academy in Lagos',
    isOnline: true,
    mutualConnections: 22
  },
  {
    id: '15',
    name: 'Dr. Maria Santos',
    title: 'Tropical Medicine Specialist',
    company: 'Médecins Sans Frontières',
    location: 'São Paulo, Brazil',
    origin: 'Afro-Brazilian Heritage',
    avatar: 'https://images.unsplash.com/photo-1594824389862-a8ec2d0f8c3d?w=150&h=150&fit=crop&crop=face',
    followers: 3450,
    connections: 890,
    skills: ['Tropical Medicine', 'Infectious Diseases', 'Global Health'],
    bio: 'Afro-Brazilian physician working on health initiatives across Portuguese-speaking Africa.',
    connectionStatus: null,
    recentActivity: 'Led malaria prevention program in Mozambique',
    isOnline: false,
    mutualConnections: 19
  },
  {
    id: '16',
    name: 'Sarah Mitchell',
    title: 'Impact Storyteller & Documentarian',
    company: 'Independent',
    location: 'Toronto, Canada',
    origin: 'Ally - European Heritage',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b35d4e1c?w=150&h=150&fit=crop&crop=face',
    followers: 2890,
    connections: 670,
    skills: ['Documentary Film', 'Social Impact', 'Visual Storytelling'],
    bio: 'Documentary filmmaker dedicated to amplifying African diaspora stories and social impact initiatives.',
    connectionStatus: 'pending',
    recentActivity: 'Released "Bridges Across Waters" documentary',
    isOnline: true,
    mutualConnections: 14
  },
  {
    id: '17',
    name: 'Emmanuel Owusu-Ansah',
    title: 'Blockchain Infrastructure Lead',
    company: 'Polygon',
    location: 'Remote (Ghana)',
    origin: 'Kumasi, Ghana',
    avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face',
    followers: 5670,
    connections: 1340,
    skills: ['Blockchain', 'DeFi', 'Cryptocurrency'],
    bio: 'Building decentralized financial infrastructure to connect African economies with global markets.',
    connectionStatus: 'connected',
    recentActivity: 'Launched DeFi protocol for cross-border remittances',
    isOnline: true,
    mutualConnections: 33
  },
  {
    id: '18',
    name: 'Michelle Pierre-Louis',
    title: 'Climate Justice Advocate',
    company: 'Caribbean Climate Alliance',
    location: 'Miami, USA',
    origin: 'Haitian-American Heritage',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    followers: 4230,
    connections: 980,
    skills: ['Climate Advocacy', 'Environmental Justice', 'Policy Development'],
    bio: 'Haitian-American advocate connecting Caribbean and African communities on climate resilience strategies.',
    connectionStatus: null,
    recentActivity: 'Organized Pan-African Climate Summit',
    isOnline: false,
    mutualConnections: 27
  },
  {
    id: '19',
    name: 'Dr. Ahmed Osman',
    title: 'EdTech Innovation Director',
    company: 'UNICEF',
    location: 'Dubai, UAE',
    origin: 'Khartoum, Sudan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 3780,
    connections: 1120,
    skills: ['Educational Technology', 'Digital Learning', 'Child Development'],
    bio: 'Sudanese educator leveraging technology to improve learning outcomes for children across Africa.',
    connectionStatus: 'connected',
    recentActivity: 'Deployed digital classrooms in refugee camps',
    isOnline: true,
    mutualConnections: 21
  },
  {
    id: '20',
    name: 'Amina Johnson-Clarke',
    title: 'Social Entrepreneurship Professor',
    company: 'Howard University',
    location: 'Washington DC, USA',
    origin: 'African American Heritage',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    followers: 3990,
    connections: 850,
    skills: ['Social Innovation', 'Entrepreneurship', 'Academic Research'],
    bio: 'African American professor mentoring next generation of social entrepreneurs focused on African development.',
    connectionStatus: 'pending',
    recentActivity: 'Published "Diaspora Innovation Ecosystems" study',
    isOnline: true,
    mutualConnections: 38
  },
  {
    id: '21',
    name: 'Jean-Baptiste Mokoko',
    title: 'Circular Economy Consultant',
    company: 'Ellen MacArthur Foundation',
    location: 'Paris, France',
    origin: 'Brazzaville, Congo',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 2560,
    connections: 720,
    skills: ['Circular Economy', 'Sustainability Consulting', 'Resource Management'],
    bio: 'Congolese sustainability expert helping African businesses transition to circular economy models.',
    connectionStatus: null,
    recentActivity: 'Launched waste-to-value initiative in Cameroon',
    isOnline: false,
    mutualConnections: 15
  }
];

export type MockProfessional = typeof mockProfessionals[0];
